// This file is automatically generated. Do not edit it directly.
import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';
import { NativeBiometric } from 'capacitor-native-biometric';
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const capacitorStorage = {
  async getItem(key: string) {
    const { value } = await Preferences.get({ key });
    return value ?? null;
  },
  async setItem(key: string, value: string) {
    await Preferences.set({ key, value });
  },
  async removeItem(key: string) {
    await Preferences.remove({ key });
  },
};

const SUPABASE_STORAGE_SERVER = 'app.petlinkid.supabase';

const biometricStorage = {
  async getStore() {
    try {
      const credentials = await NativeBiometric.getCredentials({ server: SUPABASE_STORAGE_SERVER });
      return JSON.parse(credentials.password || '{}') as Record<string, string>;
    } catch {
      return {};
    }
  },
  async saveStore(store: Record<string, string>) {
    const serialized = JSON.stringify(store);
    await NativeBiometric.setCredentials({
      username: 'supabase',
      password: serialized,
      server: SUPABASE_STORAGE_SERVER,
    });
  },
  async getItem(key: string) {
    const store = await biometricStorage.getStore();
    return store[key] ?? null;
  },
  async setItem(key: string, value: string) {
    const store = await biometricStorage.getStore();
    store[key] = value;
    await biometricStorage.saveStore(store);
  },
  async removeItem(key: string) {
    const store = await biometricStorage.getStore();
    delete store[key];
    await biometricStorage.saveStore(store);
  },
};

const storage = Capacitor.isNativePlatform() ? biometricStorage : localStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
